CREATE DATABASE IF NOT EXISTS userservice;
CREATE DATABASE IF NOT EXISTS productmicroservice;
CREATE DATABASE IF NOT EXISTS orderservice;
CREATE DATABASE IF NOT EXISTS droneservice;
CREATE DATABASE IF NOT EXISTS paymentservice;
